# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dogovor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 588)
        self.background = QtWidgets.QWidget(Dialog)
        self.background.setGeometry(QtCore.QRect(0, -10, 641, 601))
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("#background {\n"
"background-color: rgb(170, 170, 200)\n"
"}")
        self.background.setObjectName("background")
        self.label = QtWidgets.QLabel(self.background)
        self.label.setGeometry(QtCore.QRect(150, 200, 151, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.background)
        self.label_2.setGeometry(QtCore.QRect(150, 240, 141, 20))
        self.label_2.setObjectName("label_2")
        self.viborarendatora = QtWidgets.QComboBox(self.background)
        self.viborarendatora.setGeometry(QtCore.QRect(340, 200, 151, 22))
        self.viborarendatora.setObjectName("viborarendatora")
        self.viborobjecta = QtWidgets.QComboBox(self.background)
        self.viborobjecta.setGeometry(QtCore.QRect(340, 240, 151, 22))
        self.viborobjecta.setObjectName("viborobjecta")
        self.label_3 = QtWidgets.QLabel(self.background)
        self.label_3.setGeometry(QtCore.QRect(150, 280, 151, 20))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.background)
        self.label_7.setGeometry(QtCore.QRect(150, 320, 151, 20))
        self.label_7.setObjectName("label_7")
        self.dataokonchaniyaarendy = QtWidgets.QDateEdit(self.background)
        self.dataokonchaniyaarendy.setGeometry(QtCore.QRect(340, 320, 151, 22))
        self.dataokonchaniyaarendy.setObjectName("dataokonchaniyaarendy")
        self.datanachalaarendy = QtWidgets.QDateEdit(self.background)
        self.datanachalaarendy.setGeometry(QtCore.QRect(340, 280, 151, 22))
        self.datanachalaarendy.setObjectName("datanachalaarendy")
        self.label_8 = QtWidgets.QLabel(self.background)
        self.label_8.setGeometry(QtCore.QRect(150, 360, 161, 20))
        self.label_8.setObjectName("label_8")
        self.datazakldogovora = QtWidgets.QDateEdit(self.background)
        self.datazakldogovora.setGeometry(QtCore.QRect(340, 360, 151, 22))
        self.datazakldogovora.setObjectName("datazakldogovora")
        self.label_9 = QtWidgets.QLabel(self.background)
        self.label_9.setGeometry(QtCore.QRect(150, 400, 161, 16))
        self.label_9.setObjectName("label_9")
        self.dataezhemes = QtWidgets.QDateEdit(self.background)
        self.dataezhemes.setGeometry(QtCore.QRect(340, 400, 151, 22))
        self.dataezhemes.setObjectName("dataezhemes")
        self.label_10 = QtWidgets.QLabel(self.background)
        self.label_10.setGeometry(QtCore.QRect(150, 440, 151, 20))
        self.label_10.setObjectName("label_10")
        self.vychislyaemayaplata = QtWidgets.QLineEdit(self.background)
        self.vychislyaemayaplata.setGeometry(QtCore.QRect(340, 440, 151, 20))
        self.vychislyaemayaplata.setObjectName("vychislyaemayaplata")
        self.label_11 = QtWidgets.QLabel(self.background)
        self.label_11.setGeometry(QtCore.QRect(150, 160, 151, 20))
        self.label_11.setObjectName("label_11")
        self.iddogovora = QtWidgets.QLineEdit(self.background)
        self.iddogovora.setGeometry(QtCore.QRect(340, 160, 151, 20))
        self.iddogovora.setObjectName("iddogovora")
        self.okey = QtWidgets.QPushButton(self.background)
        self.okey.setGeometry(QtCore.QRect(180, 530, 91, 31))
        self.okey.setObjectName("okey")
        self.okey_2 = QtWidgets.QPushButton(self.background)
        self.okey_2.setGeometry(QtCore.QRect(360, 530, 91, 31))
        self.okey_2.setObjectName("okey_2")
        self.label_4 = QtWidgets.QLabel(self.background)
        self.label_4.setGeometry(QtCore.QRect(200, 70, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Выбор арендатора:"))
        self.label_2.setText(_translate("Dialog", "Выбор объекта:"))
        self.label_3.setText(_translate("Dialog", "Дата начала аренды:"))
        self.label_7.setText(_translate("Dialog", "Дата окончания аренды:"))
        self.dataokonchaniyaarendy.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.datanachalaarendy.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_8.setText(_translate("Dialog", "Дата заключения договора:"))
        self.datazakldogovora.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_9.setText(_translate("Dialog", "Дата ежемесячной оплаты:"))
        self.dataezhemes.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_10.setText(_translate("Dialog", "Месячная арендная плата:"))
        self.label_11.setText(_translate("Dialog", "Договор №:"))
        self.okey.setText(_translate("Dialog", "ОК"))
        self.okey_2.setText(_translate("Dialog", "Отмена"))
        self.label_4.setText(_translate("Dialog", "Создание договора"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
