# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewArendatelFiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewObject(object):
    def setupUi(self, NewObject):
        NewObject.setObjectName("NewObject")
        NewObject.setFixedSize(585, 527)
        self.frame = QtWidgets.QFrame(NewObject)
        self.frame.setGeometry(QtCore.QRect(0, 0, 591, 531))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(-250, 420, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 110, 91, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 150, 111, 41))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(150, 230, 141, 41))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(150, 270, 141, 41))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(290, 120, 161, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 160, 161, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 240, 161, 20))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(290, 280, 161, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(150, 190, 61, 41))
        self.label_6.setObjectName("label_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(292, 200, 161, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(150, 310, 141, 41))
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(290, 320, 161, 20))
        self.lineEdit_6.setDragEnabled(False)
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(150, 350, 141, 41))
        self.label_9.setObjectName("label_9")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(290, 360, 161, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(110, 30, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(NewObject)
        self.buttonBox.accepted.connect(NewObject.accept) # type: ignore
        self.buttonBox.rejected.connect(NewObject.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewObject)
        NewObject.setTabOrder(self.lineEdit_6, self.lineEdit_4)
        NewObject.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        NewObject.setTabOrder(self.lineEdit_5, self.lineEdit)
        NewObject.setTabOrder(self.lineEdit, self.lineEdit_2)
        NewObject.setTabOrder(self.lineEdit_2, self.lineEdit_7)

    def retranslateUi(self, NewObject):
        _translate = QtCore.QCoreApplication.translate
        NewObject.setWindowTitle(_translate("NewObject", "Новый объект"))
        self.label.setText(_translate("NewObject", "Наименование:"))
        self.label_2.setText(_translate("NewObject", "ФИО руководителя:"))
        self.label_4.setText(_translate("NewObject", "Юридический адрес:"))
        self.label_7.setText(_translate("NewObject", "Контактный телефон:"))
        self.label_6.setText(_translate("NewObject", "БИН:"))
        self.label_8.setText(_translate("NewObject", "Номер лицензии:"))
        self.label_9.setText(_translate("NewObject", "Дата действия лицензии:"))
        self.label_3.setText(_translate("NewObject", "Добавление Юридического лица"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewObject = QtWidgets.QDialog()
    ui = Ui_NewObject()
    ui.setupUi(NewObject)
    NewObject.show()
    sys.exit(app.exec_())
