# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewArendatel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import images

class Ui_fizcreate(object):
    def setupUi(self, fizcreate):
        fizcreate.setObjectName("fizcreate")
        fizcreate.resize(465, 493)
        icon = QIcon((":/logocompany.png"))
        fizcreate.setWindowIcon(icon)
        self.background = QtWidgets.QFrame(fizcreate)
        self.background.setGeometry(QtCore.QRect(-30, -10, 531, 601))
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("#background {\n"
"background-color: rgb(170, 170, 127)\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.fiolabel = QtWidgets.QLabel(self.background)
        self.fiolabel.setGeometry(QtCore.QRect(120, 150, 61, 41))
        self.fiolabel.setObjectName("fiolabel")
        self.passlabel = QtWidgets.QLabel(self.background)
        self.passlabel.setGeometry(QtCore.QRect(120, 190, 121, 41))
        self.passlabel.setObjectName("passlabel")
        self.adresslabel = QtWidgets.QLabel(self.background)
        self.adresslabel.setGeometry(QtCore.QRect(120, 270, 141, 41))
        self.adresslabel.setObjectName("adresslabel")
        self.numlabel = QtWidgets.QLabel(self.background)
        self.numlabel.setGeometry(QtCore.QRect(120, 310, 141, 41))
        self.numlabel.setObjectName("numlabel")
        self.fio = QtWidgets.QLineEdit(self.background)
        self.fio.setGeometry(QtCore.QRect(260, 160, 161, 20))
        self.fio.setObjectName("fio")
        self.passport = QtWidgets.QLineEdit(self.background)
        self.passport.setGeometry(QtCore.QRect(260, 200, 161, 20))
        self.passport.setObjectName("passport")
        self.adress = QtWidgets.QLineEdit(self.background)
        self.adress.setGeometry(QtCore.QRect(260, 280, 161, 20))
        self.adress.setText("")
        self.adress.setObjectName("adress")
        self.phone = QtWidgets.QLineEdit(self.background)
        self.phone.setGeometry(QtCore.QRect(260, 320, 161, 20))
        self.phone.setObjectName("phone")
        self.iinlabel = QtWidgets.QLabel(self.background)
        self.iinlabel.setGeometry(QtCore.QRect(120, 230, 61, 41))
        self.iinlabel.setObjectName("iinlabel")
        self.iin = QtWidgets.QLineEdit(self.background)
        self.iin.setGeometry(QtCore.QRect(262, 240, 161, 20))
        self.iin.setObjectName("iin")
        self.nazavanie = QtWidgets.QLabel(self.background)
        self.nazavanie.setGeometry(QtCore.QRect(70, 60, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.nazavanie.setFont(font)
        self.nazavanie.setObjectName("nazavanie")
        self.okey = QtWidgets.QPushButton(self.background)
        self.okey.setGeometry(QtCore.QRect(154, 420, 91, 31))
        self.okey.setObjectName("okey")
        self.cancel = QtWidgets.QPushButton(self.background)
        self.cancel.setGeometry(QtCore.QRect(300, 420, 91, 31))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(fizcreate)
        QtCore.QMetaObject.connectSlotsByName(fizcreate)

    def retranslateUi(self, fizcreate):
        _translate = QtCore.QCoreApplication.translate
        fizcreate.setWindowTitle(_translate("fizcreate", "Новое физ-лицо"))
        self.fiolabel.setText(_translate("fizcreate", "ФИО:"))
        self.passlabel.setText(_translate("fizcreate", "Паспортные данные:"))
        self.adresslabel.setText(_translate("fizcreate", "Адрес:"))
        self.numlabel.setText(_translate("fizcreate", "Контактный телефон:"))
        self.iinlabel.setText(_translate("fizcreate", "ИИН:"))
        self.nazavanie.setText(_translate("fizcreate", "Добавление Физического лица"))
        self.okey.setText(_translate("fizcreate", "ОК"))
        self.cancel.setText(_translate("fizcreate", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fizcreate = QtWidgets.QDialog()
    ui = Ui_fizcreate()
    ui.setupUi(fizcreate)
    fizcreate.show()
    sys.exit(app.exec_())
