# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditArendatel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QPushButton
import MySQLdb as mdb
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import images

class Ui_fizedit(object):
    def setupUi(self, fizedit,selected_row):
        self.selected_row = selected_row
        fizedit.setObjectName("fizedit")
        fizedit.setFixedSize(465, 493)
        icon = QIcon((":/logocompany.png"))
        fizedit.setWindowIcon(icon)
        self.background = QtWidgets.QFrame(fizedit)
        self.background.setGeometry(QtCore.QRect(-30, -10, 531, 601))
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("#background {\n"
"background-color: rgb(170, 170, 127)\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.fiolabel = QtWidgets.QLabel(self.background)
        self.fiolabel.setGeometry(QtCore.QRect(120, 150, 61, 41))
        self.fiolabel.setObjectName("fiolabel")
        self.passlabel = QtWidgets.QLabel(self.background)
        self.passlabel.setGeometry(QtCore.QRect(120, 190, 121, 41))
        self.passlabel.setObjectName("passlabel")
        self.adresslabel = QtWidgets.QLabel(self.background)
        self.adresslabel.setGeometry(QtCore.QRect(120, 270, 141, 41))
        self.adresslabel.setObjectName("adresslabel")
        self.numlabel = QtWidgets.QLabel(self.background)
        self.numlabel.setGeometry(QtCore.QRect(120, 310, 141, 41))
        self.numlabel.setObjectName("numlabel")
        self.fio = QtWidgets.QLineEdit(self.background)
        self.fio.setGeometry(QtCore.QRect(260, 160, 161, 20))
        self.fio.setObjectName("fio")
        self.passport = QtWidgets.QLineEdit(self.background)
        self.passport.setGeometry(QtCore.QRect(260, 200, 161, 20))
        self.passport.setObjectName("passport")
        self.adress = QtWidgets.QLineEdit(self.background)
        self.adress.setGeometry(QtCore.QRect(260, 280, 161, 20))
        self.adress.setText("")
        self.adress.setObjectName("adress")
        self.phone = QtWidgets.QLineEdit(self.background)
        self.phone.setGeometry(QtCore.QRect(260, 320, 161, 20))
        self.phone.setObjectName("phone")
        self.iinlabel = QtWidgets.QLabel(self.background)
        self.iinlabel.setGeometry(QtCore.QRect(120, 230, 61, 41))
        self.iinlabel.setObjectName("iinlabel")
        self.iin = QtWidgets.QLineEdit(self.background)
        self.iin.setGeometry(QtCore.QRect(262, 240, 161, 20))
        self.iin.setObjectName("iin")
        self.iin.setReadOnly(True)
        self.nazavanie = QtWidgets.QLabel(self.background)
        self.nazavanie.setGeometry(QtCore.QRect(50, 60, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.nazavanie.setFont(font)
        self.nazavanie.setObjectName("nazavanie")
        self.okey = QtWidgets.QPushButton(self.background)
        self.okey.setGeometry(QtCore.QRect(204, 420, 91, 31))
        self.okey.setObjectName("okey")
        self.okey.clicked.connect(lambda: self.editarendatortodatabase())
        

        self.retranslateUi(fizedit)
        QtCore.QMetaObject.connectSlotsByName(fizedit)

    def editarendatortodatabase(self):
        try:
            db = mdb.connect('localhost', 'root', 'root', 'arenda')
            mycursor = db.cursor()
            fio3 = self.fio.text()
            pass3 = self.passport.text()
            iin333 = self.iin.text()
            adress3 = self.adress.text()
            phone3 = self.phone.text()
            query = f"UPDATE fizlitca SET FIO='{fio3}', Passport='{pass3}', Adress='{adress3}', Phone='{phone3}' WHERE IIN = '{iin333}'"
            mycursor.execute(query)
            db.commit()
            error = QMessageBox()
            error.setWindowTitle('Успех')
            error.setText('Данные отредактированы!')
            error.buttons = QtWidgets.QMessageBox.Ok
            error.exec_()
            
        

        except mdb.Error as e:
                print (e)
                error = QMessageBox()
                error.setText('Переделывай, данные не внесены!')
                error.exec_()



    def retranslateUi(self, fizedit):
        _translate = QtCore.QCoreApplication.translate
        fizedit.setWindowTitle(_translate("fizedit", "Новый объект"))
        self.fiolabel.setText(_translate("fizedit", "ФИО:"))
        self.passlabel.setText(_translate("fizedit", "Паспортные данные:"))
        self.adresslabel.setText(_translate("fizedit", "Адрес:"))
        self.numlabel.setText(_translate("fizedit", "Контактный телефон:"))
        self.iinlabel.setText(_translate("fizedit", "ИИН:"))
        self.nazavanie.setText(_translate("fizedit", "Редактирование Физического лица"))
        self.okey.setText(_translate("fizedit", "ОК"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fizedit = QtWidgets.QDialog()
    ui = Ui_fizedit()
    ui.setupUi(fizedit)
    fizedit.show()
    sys.exit(app.exec_())
